default: &default
  adapter: mysql2
  database: crystal_trends
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: crystal_trends_development
test:
  <<: *default
  database: crystal_trends_test

production:
  <<: *default
  database: crystal_trends_productionx1
